<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Event;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class EventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $event1 = $this->createEventUAE();
        $event2 = $this->createEventUAE();
        $event3 = $this->createEventUAE();
        $event4 = $this->createEventUAE();
        $event5 = $this->createEventUAE();
        $event6 = $this->createEventUAE();
        $event7 = $this->createEventUAE();
        $event8 = $this->createEventUAE();
        $event9 = $this->createEventUAE();
        $event1 = $this->createEventKSA();
        $event2 = $this->createEventKSA();
        $event3 = $this->createEventKSA();
        $event4 = $this->createEventKSA();
        $event5 = $this->createEventKSA();
        $event6 = $this->createEventKSA();
        $event7 = $this->createEventKSA();
        $event8 = $this->createEventKSA();
        $event9 = $this->createEventKSA();
        $event1 = $this->createEventKW();
        $event2 = $this->createEventKW();
        $event3 = $this->createEventKW();
        $event4 = $this->createEventKW();
        $event5 = $this->createEventKW();
        $event6 = $this->createEventKW();
        $event7 = $this->createEventKW();
        $event8 = $this->createEventKW();
        $event9 = $this->createEventKW();
    }

    private function createEventUAE(): Event
    {
        $event = Event::create([
            'meta' => [
                'translate' => [
                    'title_ar' => 'عنوان الفعالية',
                    'description_ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع.
ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق.
هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً.',
                    'title_en' => 'Event Title',
                    'description_en' => '<p><strong>This text is an example that can be replaced in the same space, where you can create this text from the Arabic text generator, where you can generate text or other texts in addition to increasing the number of characters generated by the application.
Arabic text templates Increase paragraphs as you want, Arabic text is useful for website designers in particular, where the client needs in a linguistic image to design the site.
Hence, the designer must put temporary texts on the general design of the client. The shape is perfect. The role of the Arabic text generator is to save the designer the trouble of searching for an alternative text for him with the topic he is talking about, so the design appears in an inappropriate manner.
<hr>
It is superimposed on a coordinator, or even incomprehensible. Because it is still an alternative and temporary text.</strong></p>',
                ],

            ],
            'thumbnail' => 'https://flick.ae/wp-content/themes/flick_new/images/new-works/coca-cola.jpg',
            'date' => Carbon::now(),
            'country_id' => Country::whereCode('AE')->first()->id,
            'alt' => 'Event test image',
        ]);
            $event->slug = strtolower(explode(' ', trim($event->meta['translate']['title_en']))[0] . $event->id);
        $event->save();
        $event->refresh();

        return $event;
    }

    private function createEventKSA(): Event
    {
        $event = Event::create([
            'meta' => [
                'translate' => [
                    'title_ar' => 'عنوان الفعالية',
                    'description_ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع.
ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق.
هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً.',
                    'title_en' => 'Event Title',
                    'description_en' => 'This text is an example that can be replaced in the same space, where you can create this text from the Arabic text generator, where you can generate text or other texts in addition to increasing the number of characters generated by the application.
Arabic text templates Increase paragraphs as you want, Arabic text is useful for website designers in particular, where the client needs in a linguistic image to design the site.
Hence, the designer must put temporary texts on the general design of the client. The shape is perfect. The role of the Arabic text generator is to save the designer the trouble of searching for an alternative text for him with the topic he is talking about, so the design appears in an inappropriate manner.
It is superimposed on a coordinator, or even incomprehensible. Because it is still an alternative and temporary text.',
                ],

            ],
            'thumbnail' => 'https://flick.ae/wp-content/themes/flick_new/images/new-works/coca-cola.jpg',
            'date' => Carbon::now(),
            'country_id' => Country::whereCode('SA')->first()->id,
        ]);
            $event->slug = strtolower(explode(' ', trim($event->meta['translate']['title_en']))[0] . $event->id);
        $event->save();
        $event->refresh();

        return $event;

    }

    private function createEventKW(): Event
    {
        $event = Event::create([
            'meta' => [
                'translate' => [
                    'title_ar' => 'عنوان الفعالية',
                    'description_ar' => 'هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.
إذا كنت تحتاج إلى عدد أكبر من الفقرات يتيح لك مولد النص العربى زيادة عدد الفقرات كما تريد، النص لن يبدو مقسما ولا يحوي أخطاء لغوية، مولد النص العربى مفيد لمصممي المواقع على وجه الخصوص، حيث يحتاج العميل فى كثير من الأحيان أن يطلع على صورة حقيقية لتصميم الموقع.
ومن هنا وجب على المصمم أن يضع نصوصا مؤقتة على التصميم ليظهر للعميل الشكل كاملاً،دور مولد النص العربى أن يوفر على المصمم عناء البحث عن نص بديل لا علاقة له بالموضوع الذى يتحدث عنه التصميم فيظهر بشكل لا يليق.
هذا النص يمكن أن يتم تركيبه على أي تصميم دون مشكلة فلن يبدو وكأنه نص منسوخ، غير منظم، غير منسق، أو حتى غير مفهوم. لأنه مازال نصاً بديلاً ومؤقتاً.',
                    'title_en' => 'Event Title',
                    'description_en' => 'This text is an example that can be replaced in the same space, where you can create this text from the Arabic text generator, where you can generate text or other texts in addition to increasing the number of characters generated by the application.
Arabic text templates Increase paragraphs as you want, Arabic text is useful for website designers in particular, where the client needs in a linguistic image to design the site.
Hence, the designer must put temporary texts on the general design of the client. The shape is perfect. The role of the Arabic text generator is to save the designer the trouble of searching for an alternative text for him with the topic he is talking about, so the design appears in an inappropriate manner.
It is superimposed on a coordinator, or even incomprehensible. Because it is still an alternative and temporary text.',
                ],

            ],
            'thumbnail' => 'https://flick.ae/wp-content/themes/flick_new/images/new-works/coca-cola.jpg',
            'date' => Carbon::now(),
            'country_id' => Country::whereCode('KW')->first()->id,
        ]);

            $event->slug = strtolower(explode(' ', trim($event->meta['translate']['title_en']))[0] . $event->id);
        $event->save();
        $event->refresh();

        return $event;
    }
}
